[package]
name = "jlcpcb-to-parquet"
version = "0.2.0"
edition = "2021"

[dependencies]
polars = { version = "0.37.0", features = ["parquet", "lazy", "object", "streaming"] }
sqlx = { version = "0.7.3", features = ["sqlite", "runtime-tokio"] }
tokio = { version = "1.36.0", features = ["full"] }
